# Generated by Django 4.2.7 on 2025-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitetoken",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("user_invite", "User Invite"),
                    ("password_reset", "Password Reset"),
                    ("company_setup", "Company Setup"),
                    ("interviewer_invite", "Interviewer Invite"),
                ],
                max_length=20,
            ),
        ),
    ]
